# Active analysis modules to run, in this order.
# Tip: Edit this during development to run ones you're working on first.
ACTIVE = [
	"biosynthesisProductionDynamics.py",
	"carRegulation.py",
	"cellCycleLength.py",
	"cellCycleLengthsCorrelation.py",
	"centralCarbonMetabolismCorrelationTimeCourse.py",
	"centralCarbonMetabolismScatter.py",
	"figure5B_E_F_G.py",
	"figure5D.py",
	"figure5H.py",
	"figureS1fluxes.py",
	"functionalUnits.py",
	"functionalUnitsFC.py",
	"growthAffectingPolymerases.py",
	# "growthRateControl.py",
	# "initiationNoiseVsFoldChange.py",
	"kineticsFluxComparison.py",
	"limitedEnzymeGlutcyslig.py",
	# "limitedEnzymeMene.py",
	"limitedEnzymeUgd.py",
	"limitedMetabolites.py",
	"massFractionSummary.py",
	"massFractionToUnity.py",
	"massShift.py",
	# "probProteinExistAndDouble.py",
	"proteinAvgCountVsBurstSize.py",
	"proteinConcentrations.py",
	"proteinCountVsFoldChange.py",
	"proteinCountsValidation.py",
	"proteinExistVsBurstSize.py",
	"proteinFoldChangeVsRnaDeg.py",
	"proteinFoldChangeVsTranscriptionEvents.py",
	"proteinFoldChangeVsTranslationEff.py",
	"proteinMassFractionFoldChange.py",
	"proteomeMassFractions.py",
	"r01_dryMass.py",
	"replication.py",
	"ribosomeProduction.py",
	"ribosomeUsage.py",
	# "rnaVsProteinPerCell.py",
	"rna_decay_03_high.py",
	"timeStep.py",
	"transcriptionEvents.py",
	"transcriptionFrequency.py",
	"transcriptionFrequencyOrdered.py",
	# "transcriptionGenomeCoverage.py",
	"transcriptionInitiationMap.py",
	"translationFrequency.py",
	"trpRegulation.py",
	"trpSynthaseCapacityVsUsage.py",
	"tyrRegulation.py",
]
