# Active analysis modules to run, in this order.
# Tip: Edit this during development to run ones you're working on first.
ACTIVE = [
	"biosynthesisProductionDynamics.py",
	"carRegulation.py",
	"cellCycleLength.py",
	"cellCycleLengthsCorrelation.py",
	"centralCarbonMetabolismCorrelationTimeCourse.py",
	"centralCarbonMetabolismScatter.py",
	"environmental_shift_fluxes.py",
	"subgenerational_transcription.py",
	"subgenerational_transcription_environment_dependence.py",
	"functionalUnits.py",
	"growthAffectingPolymerases.py",
	# "growthRateControl.py",
	# "initiationNoiseVsFoldChange.py",
	"kineticsFluxComparison.py",
	"limitedEnzymeGlutcyslig.py",
	# "limitedEnzymeMene.py",
	"limitedEnzymeUgd.py",
	"limitedMetabolites.py",
	"massFractionSummary.py",
	"massFractionToUnity.py",
	"massShift.py",
	"mene_limitations.py",
	"pabx_limitations.py",
	# "probProteinExistAndDouble.py",
	"proteinAvgCountVsBurstSize.py",
	"proteinConcentrations.py",
	"proteinCountVsFoldChange.py",
	"proteinCountsValidation.py",
	"proteinExistVsBurstSize.py",
	"proteinFoldChangeVsRnaDeg.py",
	"proteinFoldChangeVsTranscriptionEvents.py",
	"proteinFoldChangeVsTranslationEff.py",
	"proteinMassFractionFoldChange.py",
	# "proteomeMassFractions.py",
	"r01_dryMass.py",
	"replication.py",
	# "ribosomeProduction.py",
	"ribosomeUsage.py",
	# "rnaVsProteinPerCell.py",
	"rna_decay_03_high.py",
	"rnap_ribosome_doubling_time.py",
	"timeStep.py",
	"transcriptionEvents.py",
	"transcriptionFrequency.py",
	"transcriptionFrequencyOrdered.py",
	# "transcriptionGenomeCoverage.py",
	"transcriptionInitiationMap.py",
	"translationFrequency.py",
	"trpRegulation.py",
	"trpSynthaseCapacityVsUsage.py",
	"tyrRegulation.py",
]
