from __future__ import absolute_import, division, print_function

# Active analysis modules to run, in this order.
# Tip: Edit this during development to run ones you're working on first.
ACTIVE = [
	"aa_conc.py",
	"aa_supply.py",
	"aa_supply_enzymes.py",
	"biosynthesisProductionDynamics.py",
	"carRegulation.py",
	"cellCycleLength.py",
	"centralCarbonMetabolismCorrelationTimeCourse.py",
	"centralCarbonMetabolismScatter.py",
	"charging_molecules.py",
	"environmental_shift_fluxes.py",
	"functionalUnits.py",
	"functionalUnitsFC.py",
	"growthAffectingPolymerases.py",
	"kineticsFluxComparison.py",
	"limitedEnzymeGlutcyslig.py",
	"limitedEnzymeUgd.py",
	"limitedMetabolites.py",
	"massFractionSummary.py",
	"massFractionToUnity.py",
	"massShift.py",
	"mene_limitations.py",
	# "probProteinExistAndDouble.py",
	"ppgpp_regulation.py",
	"proteinAvgCountVsBurstSize.py",
	"proteinCountVsFoldChange.py",
	"proteinCountsValidation.py",
	"proteinExistVsBurstSize.py",
	"proteinFoldChangeVsRnaDeg.py",
	"proteinFoldChangeVsTranscriptionEvents.py",
	"proteinFoldChangeVsTranslationEff.py",
	"replication.py",
	"ribosomeProduction.py",
	"ribosomeUsage.py",
	# "rnaVsProteinPerCell.py",
	"rna_decay_03_high.py",
	"subgenerationalTranscription.py",
	"tf_binding.py",
	"timeStep.py",
	"transcriptionEvents.py",
	"transcriptionFrequency.py",
	"transcriptionFrequencyOrdered.py",
	# "transcriptionGenomeCoverage.py",
	"translationFrequency.py",
	"trpRegulation.py",
	"trpSynthaseCapacityVsUsage.py",
	"tyrRegulation.py",
]

TAGS = {
	'ACTIVE': ACTIVE,   # all active analyses in this category
	'CORE': [           # the default list to run in development
		"aa_conc.py",
		"aa_supply.py",
		"aa_supply_enzymes.py",
		"cellCycleLength.py",
		"massFractionSummary.py",
		"massFractionToUnity.py",
		"replication.py",
		"timeStep.py",
		],
	'DIVISION': [
		"cellCycleLength.py",
		],
	'ENVIRONMENT_SHIFT': [
		"aa_supply.py",
		"environmental_shift_fluxes.py",  # TODO(jerry): include this?
		"massShift.py",
		],
	'GROWTH': [
		"aa_conc.py",
		"aa_supply.py",
		"aa_supply_enzymes.py",
		"cellCycleLength.py",
		"charging_molecules.py",
		"growthAffectingPolymerases.py",
		"massFractionSummary.py",
		"ppgpp_regulation.py",
		],
	'METABOLISM': [
		"aa_conc.py",
		"aa_supply.py",
		"aa_supply_enzymes.py",
		"centralCarbonMetabolismCorrelationTimeCourse.py",
		"centralCarbonMetabolismScatter.py",
		"kineticsFluxComparison.py",
		"limitedMetabolites.py",
		],
	'PAPER': [
		"environmental_shift_fluxes.py",
		"functionalUnits.py",
		"functionalUnitsFC.py",
		"limitedEnzymeGlutcyslig.py",
		"limitedEnzymeUgd.py",
		"mene_limitations.py",
		"proteinAvgCountVsBurstSize.py",
		"proteinCountVsFoldChange.py",
		"proteinCountsValidation.py",
		"proteinExistVsBurstSize.py",
		"proteinFoldChangeVsRnaDeg.py",
		"transcriptionFrequencyOrdered.py",
		"trpRegulation.py",
		],
	'RNA_DEGRADATION': [
		"rna_decay_03_high.py",
		],
	'REGULATION': [
		"aa_supply.py",
		"aa_supply_enzymes.py",
		"biosynthesisProductionDynamics.py",
		"carRegulation.py",
		"tf_binding.py",
		"trpRegulation.py",
		"trpSynthaseCapacityVsUsage.py",
		"tyrRegulation.py",
		],
	'SUBGENERATIONAL': [
		"proteinAvgCountVsBurstSize.py",
		"proteinCountVsFoldChange.py",
		"proteinExistVsBurstSize.py",
		"proteinFoldChangeVsRnaDeg.py",
		"proteinFoldChangeVsTranscriptionEvents.py",
		"proteinFoldChangeVsTranslationEff.py",
		"subgenerationalTranscription.py",
		"transcriptionEvents.py",
		"transcriptionFrequency.py",
		"transcriptionFrequencyOrdered.py",
		"translationFrequency.py",
		],
	'TRANSLATION': [
		"aa_supply.py",
		"aa_supply_enzymes.py",
		"charging_molecules.py",
		"proteinFoldChangeVsTranslationEff.py",  # TODO(jerry): include this?
		"ribosomeProduction.py",
		"ribosomeUsage.py",
		"translationFrequency.py",  # TODO(jerry): include this?
		],
	'VALIDATION': [
		"proteinCountsValidation.py",
		]
	}
