# Active analysis modules to run, in this order.
# Tip: Edit this during development to run ones you're working on first.
ACTIVE = [
	"centralCarbonMetabolismCorrelationTimeCourse.py",
	"centralCarbonMetabolismScatter.py",
	"doubling_times_histogram_all.py",
	"doubling_times_violin.py",
	# "compositionFitting.py",
	# "compositionFittingByGeneration.py",
	"expression_dynamics.py",
	"growthDynamics.py",
	# "proteinFoldChangeVsTranscriptionFrequency.py",
	"histogramDoublingTime.py",
	"histogramFinalMass.py",
	"histogramGrowthRate.py",
	"initialVsFinalMass.py",
	"kinetics_flux_comparison.py",
	"mass_fraction_instantaneous_growth_rates.py",
	"massFractionSummary.py",
	# "metabolismFullFluxes.py",
	# "proteinCopyNumberDistribution.py",
	"replication.py",
	"ribosome_validation.py",
	# "rnaCopyNumberDistribution.py",
	"rnap_validation.py",
	# "transcriptFrequency.py",
	# "transcriptionGenomeCoverage.py",
	# "transcriptionGenomeCoverageSecondHalf.py",
	]
