# Simulation set workflows were created with the commands below.
# Workflows were run individually with $ qlaunch -r rapidfire --nlaunches infinite --sleep 5

# Media shifts
## Simulation set 1
DESC="Long lead in down and up shifts with regulation" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=28 N_INIT_SIMS=32 \
  VARIANT=timelines FIRST_VARIANT_INDEX=27 LAST_VARIANT_INDEX=27 \
  TRNA_ATTENUATION=1 PPGPP_REGULATION=1 MECHANISTIC_TRANSLATION_SUPPLY=1 MECHANISTIC_AA_TRANSPORT=1 AA_SUPPLY_IN_CHARGING=1 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

## Simulation set 2
DESC="Long lead in down and up shifts without mechanistic translation supply" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=28 N_INIT_SIMS=32 \
  VARIANT=timelines FIRST_VARIANT_INDEX=27 LAST_VARIANT_INDEX=27 \
  TRNA_ATTENUATION=1 PPGPP_REGULATION=1 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

## Simulation set 3
DESC="Long lead in down and up shifts without ppGpp regulation" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=28 N_INIT_SIMS=32 \
  VARIANT=timelines FIRST_VARIANT_INDEX=27 LAST_VARIANT_INDEX=27 \
  TRNA_ATTENUATION=1 MECHANISTIC_TRANSLATION_SUPPLY=1 MECHANISTIC_AA_TRANSPORT=1 AA_SUPPLY_IN_CHARGING=1 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

## Simulation set 4
DESC="Long lead in down and up shifts with no regulation" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=28 N_INIT_SIMS=32 \
  VARIANT=timelines FIRST_VARIANT_INDEX=27 LAST_VARIANT_INDEX=27 \
  TRNA_CHARGING=0 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

# Amino acid combinations in media
## Simulation set 5
DESC="Amino acid combinations in media" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=24 N_INIT_SIMS=24 \
  VARIANT=remove_aas_shift FIRST_VARIANT_INDEX=0 LAST_VARIANT_INDEX=3 \
  TRNA_ATTENUATION=1 PPGPP_REGULATION=1 MECHANISTIC_TRANSLATION_SUPPLY=1 MECHANISTIC_AA_TRANSPORT=1 AA_SUPPLY_IN_CHARGING=1 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

## Simulation set 6
DESC="Amino acid combinations in media without regulation or charging" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=24 N_INIT_SIMS=24 \
  VARIANT=remove_aas_shift FIRST_VARIANT_INDEX=0 LAST_VARIANT_INDEX=3 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  TRNA_CHARGING=0 \
  python runscripts/fireworks/fw_queue.py

# Single amino acid media
## Simulation set 7
DESC="Add one amino acid shift" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=16 N_INIT_SIMS=4 \
  VARIANT=add_one_aa_shift FIRST_VARIANT_INDEX=0 LAST_VARIANT_INDEX=20 \
  TRNA_ATTENUATION=1 PPGPP_REGULATION=1 MECHANISTIC_TRANSLATION_SUPPLY=1 MECHANISTIC_AA_TRANSPORT=1 AA_SUPPLY_IN_CHARGING=1 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

## Simulation set 8
DESC="Remove one amino acid shift" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=8 N_INIT_SIMS=4 \
  VARIANT=remove_one_aa_shift FIRST_VARIANT_INDEX=0 LAST_VARIANT_INDEX=20 \
  TRNA_ATTENUATION=1 PPGPP_REGULATION=1 MECHANISTIC_TRANSLATION_SUPPLY=1 MECHANISTIC_AA_TRANSPORT=1 AA_SUPPLY_IN_CHARGING=1 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

# Media conditions
## Simulation set 9
DESC="Conditions with regulation" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=8 N_INIT_SIMS=16 \
  VARIANT=condition FIRST_VARIANT_INDEX=0 LAST_VARIANT_INDEX=4 \
  TRNA_ATTENUATION=1 PPGPP_REGULATION=1 MECHANISTIC_TRANSLATION_SUPPLY=1 MECHANISTIC_AA_TRANSPORT=1 AA_SUPPLY_IN_CHARGING=1 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

## Simulation set 10
DESC="Conditions without regulation or charging" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=8 N_INIT_SIMS=16 \
  VARIANT=condition FIRST_VARIANT_INDEX=0 LAST_VARIANT_INDEX=4 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  TRNA_CHARGING=0 \
  python runscripts/fireworks/fw_queue.py

# ppGpp sensitivity analysis
## Simulation set 11
DESC="ppGpp sensitivity" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=8 N_INIT_SIMS=8 \
  VARIANT=ppgpp_conc FIRST_VARIANT_INDEX=0 LAST_VARIANT_INDEX=19 \
  TRNA_ATTENUATION=1 PPGPP_REGULATION=1 MECHANISTIC_TRANSLATION_SUPPLY=1 MECHANISTIC_AA_TRANSPORT=1 AA_SUPPLY_IN_CHARGING=1 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

# Expression limitations with fixed ppGpp concentrations
## Simulation set 12
DESC="ppGpp limitations - low ppGpp" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=8 N_INIT_SIMS=4 \
  VARIANT=ppgpp_limitations FIRST_VARIANT_INDEX=0 LAST_VARIANT_INDEX=36 \
  TRNA_ATTENUATION=1 PPGPP_REGULATION=1 MECHANISTIC_TRANSLATION_SUPPLY=1 MECHANISTIC_AA_TRANSPORT=1 AA_SUPPLY_IN_CHARGING=1 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

## Simulation set 13
DESC="ppGpp limitations - high ppGpp" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=8 N_INIT_SIMS=4 \
  VARIANT=ppgpp_limitations FIRST_VARIANT_INDEX=74 LAST_VARIANT_INDEX=110 \
  TRNA_ATTENUATION=1 PPGPP_REGULATION=1 MECHANISTIC_TRANSLATION_SUPPLY=1 MECHANISTIC_AA_TRANSPORT=1 AA_SUPPLY_IN_CHARGING=1 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

## Simulation set 14
DESC="ppGpp limitations with ribosomes at high ppGpp" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=8 N_INIT_SIMS=4 \
  VARIANT=ppgpp_limitations_ribosome FIRST_VARIANT_INDEX=32 LAST_VARIANT_INDEX=47 \
  TRNA_ATTENUATION=1 PPGPP_REGULATION=1 MECHANISTIC_TRANSLATION_SUPPLY=1 MECHANISTIC_AA_TRANSPORT=1 AA_SUPPLY_IN_CHARGING=1 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

## Simulation set 15
DESC="ppGpp limitations with ribosomes at high ppGpp, no ppGpp translation inhibition" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=8 N_INIT_SIMS=4 \
  VARIANT=ppgpp_limitations_ribosome FIRST_VARIANT_INDEX=32 LAST_VARIANT_INDEX=47 \
  TRNA_ATTENUATION=1 PPGPP_REGULATION=1 MECHANISTIC_TRANSLATION_SUPPLY=1 MECHANISTIC_AA_TRANSPORT=1 AA_SUPPLY_IN_CHARGING=1 \
  DISABLE_PPGPP_ELONGATION_INHIBITION=1 D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

# removing allosteric amino acid inhibition
## Simulation set 16
DESC="Remove amino acid inhibition" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=8 N_INIT_SIMS=4 \
  VARIANT=remove_aa_inhibition FIRST_VARIANT_INDEX=0 LAST_VARIANT_INDEX=35 \
  TRNA_ATTENUATION=1 PPGPP_REGULATION=1 MECHANISTIC_TRANSLATION_SUPPLY=1 MECHANISTIC_AA_TRANSPORT=1 AA_SUPPLY_IN_CHARGING=1 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py

## Simulation set 17
DESC="Remove amino acid inhibition large" PARALLEL_PARCA=1 RUN_AGGREGATE_ANALYSIS=0 \
  N_GENS=16 N_INIT_SIMS=16 \
  VARIANT=remove_aa_inhibition FIRST_VARIANT_INDEX=0 LAST_VARIANT_INDEX=7 \
  TRNA_ATTENUATION=1 PPGPP_REGULATION=1 MECHANISTIC_TRANSLATION_SUPPLY=1 MECHANISTIC_AA_TRANSPORT=1 AA_SUPPLY_IN_CHARGING=1 \
  D_PERIOD_DIVISION=1 MECHANISTIC_REPLISOME=0 TIMESTEP_MAX=1 \
  python runscripts/fireworks/fw_queue.py
