from __future__ import absolute_import, division, print_function

# constants for use as events in message passing

# environment and simulation control messages
TRIGGER_EXECUTION = 'TRIGGER_EXECUTION'
ADD_SIMULATION = 'ADD_SIMULATION'
REMOVE_SIMULATION = 'REMOVE_SIMULATION'
DIVIDE_CELL = 'DIVIDE_CELL'
PAUSE_ENVIRONMENT = 'PAUSE_ENVIRONMENT'
GLOBAL_SHUTDOWN = 'GLOBAL_SHUTDOWN'

# events for inner and outer communication
SIMULATION_INITIALIZED = 'SIMULATION_INITIALIZED'
SIMULATION_ENVIRONMENT = 'SIMULATION_ENVIRONMENT'
SIMULATION_SHUTDOWN = 'SIMULATION_SHUTDOWN'
SYNCHRONIZE_SIMULATION = 'SYNCHRONIZE_SIMULATION'
ENVIRONMENT_UPDATED = 'ENVIRONMENT_UPDATED'
CELL_DIVISION = 'CELL_DIVISION'

# events for the agent shepherd
ADD_AGENT = 'ADD_AGENT'
REMOVE_AGENT = 'REMOVE_AGENT'
SHUTDOWN_AGENT = 'SHUTDOWN_AGENT'
