from __future__ import absolute_import, division, print_function

# constants for use as events in message passing

TRIGGER_EXECUTION = 'TRIGGER_EXECUTION'
SIMULATION_INITIALIZED = 'SIMULATION_INITIALIZED'
SIMULATION_ENVIRONMENT = 'SIMULATION_ENVIRONMENT'
SIMULATION_SHUTDOWN = 'SIMULATION_SHUTDOWN'
ENVIRONMENT_UPDATED = 'ENVIRONMENT_UPDATED'
SHUTDOWN_ENVIRONMENT = 'SHUTDOWN_ENVIRONMENT'
SHUTDOWN_SIMULATION = 'SHUTDOWN_SIMULATION'
GLOBAL_SHUTDOWN = 'GLOBAL_SHUTDOWN'
